site_name: Tours
theme:
  name: material
  logo: img/sio.png

nav:
  - Documentation Tours: index.md
  - Configuration :
    - -Nutanix : nutanix.md
    - -DHCP & DNS : trs_dm.md
    - -Switch : activation_SSH.md
    - -Routeurs : routeur.md
    - -HSRP & GLPB : hsrp.md
    - -Firewall : firewall.md
  - VLAN : vlan.md