site_name: Tours
theme:
  name: material
  logo: img/sio.png

nav:
  - Documentation Tours: index.md
  - Infrastructure : infra.md  
  - Configuration :
    - -Nutanix : nutanix.md
    - -DHCP & DNS : trs_dm.md
    - -Switch : activation_SSH.md
    - -Routeurs : routeur.md
    - -HSRP & GLPB : hsrp.md
    - -Firewall : firewall.md
    - -Inter VLAN : inter_vlan.md
    - -Port mirroring : port_mirroring.md
    - -Serveur HTTP : serveur_http.md
    - -DNS : DNS.md
    - -Certificat ssl : certificat ssl.md
    - -Wordpress : wordpress.md